In [1]:
import torch 
import numpy as np

In [12]:
np.random.seed(42)
torch.manual_seed(42);

In [13]:
arr=np.random.randint(0,5,6)

In [14]:
arr

array([3, 4, 2, 4, 4, 1])

In [15]:
x=torch.from_numpy(arr)

In [16]:
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [17]:
x=x.type(torch.int64)

In [18]:
x

tensor([3, 4, 2, 4, 4, 1])

In [19]:
x.type

<function Tensor.type>

In [20]:
x.dtype

torch.int64

In [21]:
x=x.reshape(3,2)

In [22]:
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [23]:
x[:,1:]

tensor([[4],
        [4],
        [1]])

In [26]:
x**2

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [27]:
y=torch.randint(0,5,(2,3))

In [28]:
y

tensor([[2, 2, 1],
        [4, 1, 0]])

In [29]:
x.mm(y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])